Algoritmo "olamundo"
// Descrição   : Ola, mundo
// Autor(a)    : Christian P Vieira
// Data atual  : 07/01/2026
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  EscrevaL("Olá, Mundo")
  EscrevaL("Me chamo Christian Peixoto Vieira")
  EscrevaL("Tenho 35 anos, sou contador")
  EscrevaL("E estou estudando logica de programacao")
  EscrevaL("No momento terminei as aulas do Professor Gustavo Guanabara")
Fimalgoritmo